# Cloudflare Pages Configuration
name = "rebond-web"
pages_build_output_dir = "dist"
compatibility_date = "2025-10-13"

# Public
[vars]
TURNSTILE_SITE_KEY = "1x00000000000000000000AA" # Cloudflare default public

# Prod
[env.production.vars]
TURNSTILE_SITE_KEY = "0x4AAAAAAB6ZpXuSNzkjmZMQ"

# Secrets
# wrangler secret put BREVO_API_KEY
# wrangler secret put TURNSTILE_SECRET_KEY
